### ISSUE TITLE
Add a Notification "test" column

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#153]
### Task Description
- add a "test" column to the notifications and notification_history table.
- default value should be false
- column should be used to filter out test notifications in stats and reports

### Task Outcome
This will allow us to create test notifications for load testing without polluting the database. We may also want to open these numbers up to users of the Notify api, who would be doing their tests on production.

### Acceptance Criteria
- [ ] columns are added
- [ ] filters in place at all stats
- [ ] tests in place to ensure that test notifications do not impact stats
