### ISSUE TITLE
Improve performance tests, fixes and more testing scenarios

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#177]
## Description

As a Notify team member I need our tests to be working and actionable.

- The perf-test results are not pushed to the github repository [repo](https://github.com/cds-snc/notification-performance-test-results) since May, but they're still saved in the S3 buckets.
- Expand the test to a one hour test of sending emails.
- Create a blazer dashboard.

## Goals

- [x] Results reports are fixed to github.
- [ ] Results are pushed to blazer (optional if possible, but I am sure we can manage something).
- [ ] Have a test to a one hour test of sending emails
- [ ] Have a test to a one hour test of sending SMS (INTERNAL_TEST_NUMBER)
- [ ] Performance degradation should be notified to the team automatically
- [ ] Tests are running every day and results can easily be compared to previous days

**Comment by sastels** [comment]
PR for one hour email test that maxes out send rate and doesn't throw errors
https://github.com/cds-snc/notification-api/pull/2075

**Comment by jimleroyer** [comment]
@jimleroyer to review and talk to Steve today

**Comment by sastels** [comment]
discussed IRL - going to move the new test to its own run. Future work will build out different tests for other parts of Notify (ex: api frontend)

**Comment by sastels** [comment]
should also make any needed ADR changes

**Comment by sastels** [comment]
Perf tests have been fixed to run as they used to.
