### ISSUE TITLE
Upgrade PostgreSQL database to latest stable version

### ISSUE THREAD

**Issue by iokpala** [cds-snc/notification-planning-core#237]
# Task description

Upgrade the staging and production PostgreSQL database to latest version. We are currently sitting at version 11.9 for both staging and production environments. Upgrading will bring in all latest improvements and aligning our all of our environments will remove inconsistencies that can lead to tests that can fail depending where it runs.

# Reported Issue

On local setup it has been observed that the following `test_create_service_and_history_is_transactional` fails and it is believe this may be as a result of a race condition that happens when multiple tests on separate test workers have or are attempting to modify the database, a possible solution may be to bind a specific DB to a test worker.

```
___________________________________________________ test_create_service_and_history_is_transactional ____________________________________________________
[gw1] darwin -- Python 3.9.1 /Users/ikenna/.virtualenvs/notifications-api/bin/python

notify_db_session = <RoutingSQLAlchemy engine=postgresql://postgres:***@localhost:5432/test_notification_api_gw1>

    def test_create_service_and_history_is_transactional(notify_db_session):
        user = create_user()
        assert Service.query.count() == 0
        assert Service.get_history_model().query.count() == 0
        service = Service(
            name=None,
            email_from="email_from",
            message_limit=1000,
            restricted=False,
            created_by=user,
        )
    
        with pytest.raises(IntegrityError) as excinfo:
            dao_create_service(service, user)
    
>       assert 'column "name" violates not-null constraint' in str(excinfo.value)
E       assert 'column "name" violates not-null constraint' in '(psycopg2.errors.NotNullViolation) null value in column "name" of relation "services_history" violates not-null const...main\': None, \'organisation_id\': None, \'version\': 1}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)'
E        +  where '(psycopg2.errors.NotNullViolation) null value in column "name" of relation "services_history" violates not-null const...main\': None, \'organisation_id\': None, \'version\': 1}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)' = str(IntegrityError('(psycopg2.errors.NotNullViolation) null value in column "name" of relation "services_history" violates...bba-411a-bddd-c77810e1f71b, 1, f, null, t, null, 1000, null, null, null, null, null, t, null, null, null, null, f).\n'))
E        +    where IntegrityError('(psycopg2.errors.NotNullViolation) null value in column "name" of relation "services_history" violates...bba-411a-bddd-c77810e1f71b, 1, f, null, t, null, 1000, null, null, null, null, null, t, null, null, null, null, f).\n') = <ExceptionInfo IntegrityError tblen=23>.value

tests/app/dao/test_services_dao.py:817: AssertionError
```

It is also worth noting that this failure isn't currently happening in CI.. it may be worth investigating also what the differences may be.

# Task Outcome

* All environments providing PostgreSQL database are aligned on latest database version available.
* Ensure clear benchmarks for regression tracking during development.

### Acceptance Criteria

- [ ] PostgreSQL have been properly backed up prior to upgrade.
- [ ] PostgreSQL have been upgraded to latest version
- [ ] Tests are passing on local and remote instances without the reported flaky tests in this description.

# Additional information

There are different upgrade strategies available to us, easiest are with downtime and the more complicated without downtime. [Refer to this blog entry to get to know some](https://aws.amazon.com/blogs/database/part-1-upgrade-your-amazon-rds-for-postgresql-database-comparing-upgrade-approaches/).
