### ISSUE TITLE
Review and update the reviewers checklist on new PR

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#304]
# Description

As a code reviewer, 
I want a checklist of items to verify,
So that I can sign off on the changes with confidence
and the team' standards.

As a product manager, 
I want changes to go through a checklist,
so that risky changes have reduced impact on production.

## WHY are we building?

Not much to build but more to document.

## WHAT are we building?

Bring changes to the pull request reviewer's checklist, as discussed in our code review sessions.

## VALUE created by our solution

Avoid further incidents with this check list, such as the one that was triggered by the change introduced into production that required full API key format but did not verify if existing users were affected despite a loss in backward compatibility.

# Acceptance Criteria

- [ ] The PR reviewer action item has been updated for the API repository.
- [ ] The PR reviewer action item has been updated for the DD-API repository.
- [ ] The PR reviewer action item has been updated for the admin repository.
- [ ] The PR reviewer action item has been updated for the Terraform repository.
- [ ] The PR reviewer action item has been updated for the k8s manifests repository.
- [ ] The PR reviewer action item has been updated for the documentation repository.
- [ ] The PR reviewer action item has been updated for the lambdas repository.

# QA Steps

- [ ] Reviewed by the team for each repository changes.

# Additional information

* We can automate code coverage reported with a github comment à la Terraform.
* Test quality of the changes reported with a github comment à la Terraform.
* Dependencies risk are covered by Renovate automated PR changes.

**Comment by jimleroyer** [comment]
The PR for API is up here:
https://github.com/cds-snc/notification-api/pull/2122

**Comment by sastels** [comment]
lots of good feedback, plan to merge in today.

**Comment by jimleroyer** [comment]
Merged API PR today, and opened & merged one for utils as well.

**Comment by ben851** [comment]
Aiming to do one per day!

**Comment by ben851** [comment]
Jimmy has to do three today!

**Comment by jimleroyer** [comment]
New PRs:

dd-api: https://github.com/cds-snc/notification-document-download-api/pull/160
admin: https://github.com/cds-snc/notification-admin/pull/1772
terraform: https://github.com/cds-snc/notification-terraform/pull/1191 (this one might require some additional changes due to its nature)

**Comment by jimleroyer** [comment]
manifests: https://github.com/cds-snc/notification-manifests/pull/2458
documentation: https://github.com/cds-snc/notification-documentation/pull/146
lambdas: https://github.com/cds-snc/notification-lambdas/pull/68
