### ISSUE TITLE
Terraform recreation of New Relic Alert Conditions/Policies and Entities

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#380]
# Description

As an ops lead,
I want to have the [NewRelic integration wired into Terraform](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs),
So that I can boot it up anytime I need it,
and make maintenance easier overall.

## WHY are we building?

Easier maintenance; BCP.

## WHAT are we building?

[Integrate NewRelic](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs) into our Terraform plan.
Create all existing alert conditions using Terraform

## VALUE created by our solution

Replication, stability, maintenance.

# Tasks

- [ ] Recreate Alert Conditions
- [ ] Recreate Alert Policies
- [ ] Recreate Entities
- [ ] Write data code to link everything without literal id references

# Acceptance Criteria

- [ ] NewRelic is wired into our TF setup.
- [ ] [NewRelic's alarms](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition) are defined in our TF definition files.

# QA Steps

- [x] Tested against our NewRelic instance.
- [x] all previously existing alert conditions have been duplicated

**Comment by P0NDER0SA** [comment]
starting work on migrating the alerts

**Comment by P0NDER0SA** [comment]
PR in draft for all actual functional alerts (they only are functional for the lambda apis).  Can discuss.
https://github.com/cds-snc/notification-terraform/pull/1436

**Comment by P0NDER0SA** [comment]
Jimmy will QA this one (Pond might watch)

**Comment by P0NDER0SA** [comment]
This was merged!  it's in production.  Looks good... But we really want to try and get one of the alert conditions to triggers and notify slack just so we know for sure they're all working.

Made a list of the existing alert conditions
