### ISSUE TITLE
Integrate Slack within NewRelic/Terraform

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#381]
# Description

As an ops lead,
I want to have the [NewRelic Slack integration wired into Terraform](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs),
So that I can get notified anytime I need it,
and get this setup automated if we need to recreate the NewRelic in a new env.

## WHY are we building?

Easier maintenance; BCP.

## WHAT are we building?

[Integrate NewRelic](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs) into our Terraform plan, especially with the Slack integration.

## VALUE created by our solution

Replication, stability, maintenance.

# Tasks

- [ ] Integrate Slack within Terraform for NewRelic.

# Acceptance Criteria

- [ ] Slack is wired into our NewRelic TF setup.

# QA Steps

- [ ] We can still throw an alert via the new Slack setup.

**Comment by P0NDER0SA** [comment]
Looks to be working.  Opening a PR soon.

**Comment by P0NDER0SA** [comment]
PR open for review!  I've cleaned out all of the dev ones and we fcan verify if these get created on merge TF apply

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-terraform/pull/1430
