### ISSUE TITLE
Business Continuity Planning and Disaster Recovery

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning-core#40]
_Business Continuity Planning and Disaster Recovery_

## Description

As a Notify user, service owner or CIO/ADM in the government, I need to have awareness of, and have access to, GC Notify's BCP and DR plan so that I can have confidence giving authorization for my team to use Notify, or if I'm a sender, so I have confidence using Notify. 

_WHY are we building?_

As we mature GC Notify, we have identified areas of our BCP that could be improved and matured and we want to be continuously iterating on our processes and documentation.

_WHAT are we building?_

A more robust BCP/DR plan with more documentation

_VALUE created by our solution_

The GC Notify team will have good documentation and plans to follow in the event GC Notify or parts of our infrastructure go down and we need to stand up a new instance or do a fail over to a secondary system from the primary system.

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given the event that all of, or parts of GC Notify service are brought down by bad actor, natural disaster, or other event, when the GC Notify team puts the BCP and/or Disaster Recovery plan into action, then the team is able to follow the steps and processes laid out and bring the parts of the service, or the entire service back up within X number of hours.  

- [ ] List of critical business processes for GC Notify are identified
- [ ] List of scenarios that could bring down GC Notify or parts of our infrastructure are identified
- [ ] Plans and processes are drafted by SRE/Notify teams for business continuity and disaster recover
- [ ] Recovery Time Objective = ?
- [ ] Recovery Point Objective = ?
- [ ] Include scenario for if Github is down

If this user story emerged from User Research insights:
- [x] Link to security issue in Airtable https://airtable.com/appABo5w7s1QNwcPP/tbly7xWWiYbftS8u8/viwg0s3dA8xbBpXwg/recsiDAI69tSoYbAj?blocks=hide

* Security controls in place

## QA Steps

- [ ] Table top exercise to run through the new BCP/DR process to simulate a real world scenario where those plans would be needed and put into effect

**Comment by jimleroyer** [comment]
Closing as this was supplanted by https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/27 , which is more up to date and contains individual tasks that were performed for the disaster recovery effort.
