### ISSUE TITLE
Upgrade production environments to Python 3.12

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#419]
# Description

As a GCNotify developer,
I want to upgrade to latest Python stable version,
So that I can benefit from latest improvements of the language,
And upgrade libraries to the latest that requires it.

## WHY are we building?

Several improvements from Python 3.10 to 3.12 will benefit us:

* Speed improvements
* Language improvements
* Security and bug fixes
* Library upgrades

## WHAT are we building?

Upgrading the used Python library in production for our stack from 3.10 to 3.12. All repositories hosting production code should be upgraded to 3.12.

* notification-api
* notification-document-download-api
* notification-admin
* notification-utils
* notification-lambdas
* _Anything else?_

## VALUE created by our solution

Staying up to date with dependencies and getting a faster Python execution environment.

# Acceptance Criteria

All repositories hosting Python production code should be upgraded. This card is an epic and will be completed once subtasks are completed.

# QA Steps

- [ ] Run a smoke tests against the new upgraded environment.
- [ ] Run a bug bash with the team to test all upgraded components.
- [ ] Run a stress test against the new upgraded environment.
- [ ] Run in staging for at least a few days to ensure it's sane before pushing to production

**Comment by jimleroyer** [comment]
Closing as this is supplanted by epic task https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/355
