### ISSUE TITLE
Overhaul the release mechanisms for the apps

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#487]
# Description

As a developer of notify, I want our release process to be consistent between staging and development so that I can have a high confidence that production releases will work in the same way staging did.

## WHY are we building?

Staging and production release processes differ right now, causing confusion in troubleshooting and also creating risk when doing a production release.

We are migrating to helmfile for the releases, which will require changes to the release process, so we may as well overhaul it all at once.

## WHAT are we building?

A release process that can be consistent between staging and production but is automated for staging and requires a button click for production.

## VALUE created by our solution

Increased stability, easier to troubleshoot

# Acceptance Criteria

- [ ] Production and Staging use the same method for releasing
- [ ] Staging automatically deploys as it does now
- [ ] Production releases are triggered by the PR Bot
- [ ] ADR documenting the new release process is completed

# QA Steps

- [ ] Tested in a realistic production scenario
