### ISSUE TITLE
Tune celery workers to increase email send rate

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning-core#80]
_Increase email send rate_

## User story

As an ops lead, 
I want Notify celery instances to scale up more
So that it can send more emails per second.

## WHY are we building?

Send more emails per second.

## WHAT are we building?

From technical requirements to document and testing, this task should cover necessary steps to increase our overall capacity.

## VALUE created by our solution

Increase capacity to send more notifications.

# Acceptance Criteria** (Definition of done) 

- [x] We have a higher sustained email send rate
- [x] Check that our alarms will warn us if our celery workers are running out of CPU
- [x] Run performance tests against the new Celery workers setup.

# Additional information

* [AWS guidance on kubernetes scaling](https://aws.github.io/aws-eks-best-practices/scalability/docs/)
* Rely on corresponding ADR tasks to know how much we can send emails rate per second (e.g. cds-snc/notification-planning#339). 
* Might need to do some investigation with AWS because they have a default of a rate of 25/second, but possible to increase this number with justification.

**Comment by ben851** [comment]
- Ran baseline performance tests against staging yesterday
- Creating a PR today to increase CPU requests on celery workers

Performance test results:
https://docs.google.com/spreadsheets/d/1bAoaO8YDRHq_J158e3y6sxGTNltHPg-QQSvVBTeGcVQ/edit#gid=0

**Comment by ben851** [comment]
Will continue to refine and test this week.

**Comment by sastels** [comment]
upgraded instances to m6i.large, scaled to 60 pods with 4466 emails / min. Almost maxing out memory, next step is to upgrade instances to ones with more memory and scale further.

**Comment by sastels** [comment]
upgraded to r5a.large. node group is "Degraded" however.

**Comment by ben851** [comment]
Reason for degraded status is that the r5a.large is not available in one of 3 ca-central availability zones. We will continue with perf test to prove concept, and then re-evaluate node sizes.

**Comment by sastels** [comment]
- switched to r5.large, which is available on all our AZs.
- ran on 73 pods, got sustained 5603 emails / minute.
- ran a small (5000) sms test with our internal test number (does everything up to actually sending to AWS). Got up to 1600 sms / minute (still scaling up), well over our current 1200 sms fragments / minute.

**Comment by sastels** [comment]
tweaked celery pod scale up to avoid problematic  kubelet events. Restricting to an increase of 12 every 45 seconds seems a good balance of ramp up speed and preventing potentially damaging cpu usage spikes.

**Comment by jimleroyer** [comment]
Next step is to get karpenter.sh in for scaling up with more desired control. Will be outside of the scope of this card though.

**Comment by sastels** [comment]
PRs to set the `deliver_sms` rate limiting via an env var:
api: [use config variable for deliver_sms rate limiting](https://github.com/cds-snc/notification-api/pull/1979)
manifests: [feat: Celery deliver sms rate limit env variable](https://github.com/cds-snc/notification-manifests/pull/1995)

**Comment by ben851** [comment]
Steve will begin looking at these this morning

**Comment by ben851** [comment]
Waiting on Karpenter parity in production

**Comment by sastels** [comment]
scaled staging to 40 celery, 20 sms-send pods, tested.
Next step is to [deploy this to prod](https://github.com/cds-snc/notification-manifests/pull/2071).

Note that we'll need to first put celery back on karpenter pods.

**Comment by jimleroyer** [comment]
We'll test with higher constant volume to replicate a production like realistic scenario.

**Comment by sastels** [comment]
[Tested with 200K emails, 30K SMS](https://gcdigital.slack.com/archives/C05K8349YCR/p1696949717368499).
- send rates roughly as expected
- had to redeploy celery part way through to fix CWAgent bug

[Tested again Wednesday](https://gcdigital.slack.com/archives/C05K8349YCR/p1697044944531829), this time the CWAgent errors were fixed. send rates as expected, no stalled messages.

**Comment by sastels** [comment]
Can merge 
https://github.com/cds-snc/notification-manifests/pull/2071
whenever celery is back in karpenter and scaling again.

**Comment by jimleroyer** [comment]
Karpenter is back in production! But let's give it a few days to make sure this is stable.

**Comment by sastels** [comment]
More deliver_email to their own deployment of pods. This will allow us to scale them up without scaling up the rest of the (non-sms) system.
https://github.com/cds-snc/notification-manifests/pull/2118

**Comment by sastels** [comment]
will merge today (staging only) and test

**Comment by sastels** [comment]
in staging. needs testing.
should lower the SQS timeout to 26 seconds for send-email-high on staging before testing.

**Comment by jimleroyer** [comment]
Steve was on ops lead in the past business days so he didn't have a chance to work much on these cards.

**Comment by sastels** [comment]
will merge PR to lower send-email-high queue timeout and do a soak / load test

**Comment by jimleroyer** [comment]
Karpenter work was done along with necessary tests 1 year ago. We are upscaling nodes on a per-demand basis now since then. This is done and can be closed.
